version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: cron
      cronjob: "0 18 * * *"
      timezone: "Europe/Tallinn"
    groups:
      all-updates:
        applies-to: version-updates
        patterns:
          - "*"
